[nginx-grafana]
enabled  = true
filter   = nginx-grafana
logpath  = /var/lib/docker/volumes/coin_pusher_nginx_logs/_data/grafana.log
maxretry = 5
findtime = 60
bantime  = 3600
action   = iptables-multiport[name=grafana, port="80,443", protocol=tcp]
