/var/lib/docker/volumes/coin_pusher_nginx_logs/_data/grafana.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    size 10M
    postrotate
        docker kill --signal=USR1 $(docker ps -qf name=nginx) 2>/dev/null || true
    endscript
}
